import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import{Crown,Gift,Home,Info,Play,ShieldCheck,Store,Volume2,VolumeX,X}from'lucide-react';import{audio}from'./audio';import{SYMBOLS,spin,SymbolId}from'./engine/SlotEngine';import{award,canSpin,Economy,initialState,LIMITS,load,normalize,remaining,save,wager}from'./engine/Economy';import'./styles.css';
const fmt=(n:number)=>Math.floor(n).toLocaleString(); const bets=[25,50,100,250,500];
function App(){const[state,setState]=useState<Economy>(()=>normalize(load()));const[bet,setBet]=useState(50);const[board,setBoard]=useState<SymbolId[][]>(()=>spin(0).matrix);const[spinning,setSpinning]=useState(false);const[msg,setMsg]=useState('THE BLOCKCHAIN NEVER SLEEPS');const[modal,setModal]=useState<'shop'|'info'|'ad'|null>(null);const[muted,setMuted]=useState(false);useEffect(()=>save(state),[state]);
 const go=()=>{if(spinning)return;if(!canSpin(state,bet)){setMsg(state.balance<bet?'CLAIM A REFILL TO KEEP PLAYING':'DAILY PLAY LIMIT REACHED');setModal(state.balance<bet?'shop':'ad');return}setSpinning(true);setMsg('MINING THE NEXT BLOCK…');setState(s=>wager(s,bet));let ticks=0;const timer=setInterval(()=>{setBoard(spin(0).matrix);audio.stop(ticks%5);if(++ticks===6){clearInterval(timer);const result=spin(bet);setBoard(result.matrix);setState(s=>award(s,result.totalWin));setMsg(result.bonus?`TIME GATE! +${fmt(result.totalWin)} COINS`:result.totalWin?`${result.lines} LINE WIN · +${fmt(result.totalWin)}`:'THE CHAIN MOVES ON');if(result.totalWin)audio.win();setSpinning(false)}},120)};
 const daily=()=>{const d=new Date().toISOString().slice(0,10);if(state.lastClaim===d){setMsg('DAILY DROP ALREADY CLAIMED');return}const amount=state.plan==='VIP'?5000:2500;setState(s=>({...s,balance:s.balance+amount,lastClaim:d}));setMsg(`DAILY DROP +${fmt(amount)}`);setModal(null)};
 const watch=()=>{setState(s=>({...s,adCredits:s.adCredits+2500,balance:s.balance+500}));setMsg('REWARD BREAK COMPLETE · +500 COINS');setModal(null)};
 const upgrade=()=>{setState(s=>({...s,plan:'VIP'}));setMsg('VIP PREVIEW ENABLED');setModal(null)};
 const smash=()=>{if(!state.vault)return;setState(s=>({...s,balance:s.balance+s.vault,vault:0}));setMsg('VAULT SMASHED!')};
 return <main><header><div className="brand"><span>Æ</span><div><b>AEON</b><small>CRYPTO CONQUEST</small></div></div><button className="icon" onClick={()=>setMuted(audio.toggle())}>{muted?<VolumeX/>:<Volume2/>}</button></header>
 <section className="ticker"><i/> AEON NETWORK <b>BLOCK #840,021</b><span>FOR ENTERTAINMENT ONLY · NO REAL CRYPTO</span></section>
 <section className="wallet"><div><small>BALANCE</small><strong>◈ {fmt(state.balance)}</strong></div><button onClick={()=>setModal('shop')}><Gift/> DAILY DROP</button><div><small>{state.plan} LIMIT LEFT</small><strong>{fmt(Math.max(0,remaining(state)))}</strong></div></section>
 <section className="machine"><div className="machine-top"><span>⚡ MEGA HASH</span><b>GRAND <em>2,450,880</em></b><span>5 PAYLINES</span></div><div className={'reels '+(spinning?'spinning':'')}>{board.map((row,r)=>row.map((id,c)=><div className={'symbol '+id.toLowerCase()} key={`${r}-${c}`}><span>{SYMBOLS[id].glyph}</span><small>{id}</small></div>))}</div><div className="message">{msg}</div><div className="controls"><button onClick={()=>setBet(bets[(bets.indexOf(bet)-1+bets.length)%bets.length])}>−</button><div><small>TOTAL BET</small><b>◈ {bet}</b></div><button className="spin" onClick={go} disabled={spinning}><Play fill="currentColor"/>{spinning?'SPINNING':'SPIN'}</button><button onClick={()=>setBet(bets[(bets.indexOf(bet)+1)%bets.length])}>+</button></div></section>
 <section className="vault"><div><small>PIGGY VAULT</small><b>◈ {fmt(state.vault)} / 5,000</b><progress value={state.vault} max="5000"/></div><button onClick={smash} disabled={!state.vault}>SMASH</button></section>
 <section className="promo"><div><small>REWARD BREAK</small><b>Discover apps, tools & creator offers</b><p>Promotional placements can feature your products or disclosed affiliate partners.</p></div><button onClick={()=>setModal('ad')}>VIEW OFFER</button></section>
 <nav><button className="active"><Home/>CASINO</button><button onClick={()=>setModal('shop')}><Store/>SHOP</button><button onClick={()=>setModal('info')}><Info/>FAIR PLAY</button></nav>
 {modal&&<div className="overlay"><div className="modal"><button className="close" onClick={()=>setModal(null)}><X/></button>{modal==='shop'&&<><Crown className="heroIcon"/><h2>Choose your route</h2><p>Coins are virtual, have no cash value, and cannot be withdrawn or exchanged.</p><div className="plans"><button onClick={daily}><b>Free daily drop</b><span>+2,500 coins · once daily</span></button><button onClick={upgrade}><b>AEON VIP preview</b><span>No interruption ads · larger daily play allowance</span></button></div></>}{modal==='ad'&&<><Gift className="heroIcon"/><h2>Reward break</h2><p>This demo simulates a clearly labeled sponsored or house promotion. A production ad SDK can replace it later.</p><button className="primary" onClick={watch}>COMPLETE DEMO REWARD</button><small>Reward: 500 coins + 2,500 daily play allowance</small></>}{modal==='info'&&<><ShieldCheck className="heroIcon"/><h2>Fair-play promise</h2><p>Aeon is a simulated casino-style entertainment game. It does not offer gambling, real cryptocurrency, investments, prizes, cash-outs, or transferable assets.</p><ul><li>Random outcomes use disclosed weighted symbols.</li><li>Purchases never promise financial return.</li><li>Sponsored and affiliate placements must be labeled.</li><li>Parental guidance and responsible play controls are required for release.</li></ul><button className="primary" onClick={()=>setModal(null)}>UNDERSTOOD</button></>}</div></div>}</main>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
